# Generated by Django 5.2.7 on 2025-12-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_and_more'),
        ('hotels', '0007_make_room_type_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type_requested',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Double'), ('deluxe', 'Deluxe King'), ('suite', 'Family Suite'), ('penthouse', 'Penthouse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
