# Generated by Django 5.2.7 on 2025-12-18 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_type', models.CharField(choices=[('primary', 'Primary Guest'), ('additional', 'Additional Guest')], default='primary', max_length=20)),
                ('full_name', models.CharField(help_text='Full name as on passport/ID', max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('other', 'Other')], default='passport', max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(help_text='Address as shown on passport/ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to='bookings.booking')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['guest_type', 'full_name'],
            },
        ),
    ]
