# Generated by Django 5.2.7 on 2025-12-20 18:42

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_no_show_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingguest',
            name='id_number',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='id_number',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
