# Generated by Django 5.2.7 on 2025-12-20 18:42

from django.db import migrations


def encrypt_existing_data(apps, schema_editor):
    """
    Encrypt existing plaintext id_number values in BookingGuest and CheckInRecord.

    The EncryptedCharField automatically encrypts on save, so we just need to
    re-save each record with an existing plaintext id_number.
    """
    from core.encryption import encrypt_value, is_encrypted

    BookingGuest = apps.get_model('bookings', 'BookingGuest')
    CheckInRecord = apps.get_model('bookings', 'CheckInRecord')

    # Encrypt BookingGuest id_numbers
    for guest in BookingGuest.objects.exclude(id_number='').exclude(id_number__isnull=True):
        if guest.id_number and not is_encrypted(guest.id_number):
            # Directly update the raw value in the database
            BookingGuest.objects.filter(pk=guest.pk).update(
                id_number=encrypt_value(guest.id_number)
            )

    # Encrypt CheckInRecord id_numbers
    for record in CheckInRecord.objects.exclude(id_number='').exclude(id_number__isnull=True):
        if record.id_number and not is_encrypted(record.id_number):
            CheckInRecord.objects.filter(pk=record.pk).update(
                id_number=encrypt_value(record.id_number)
            )


def decrypt_existing_data(apps, schema_editor):
    """
    Reverse migration: decrypt id_number values back to plaintext.
    """
    from core.encryption import decrypt_value, is_encrypted

    BookingGuest = apps.get_model('bookings', 'BookingGuest')
    CheckInRecord = apps.get_model('bookings', 'CheckInRecord')

    # Decrypt BookingGuest id_numbers
    for guest in BookingGuest.objects.exclude(id_number='').exclude(id_number__isnull=True):
        if guest.id_number and is_encrypted(guest.id_number):
            BookingGuest.objects.filter(pk=guest.pk).update(
                id_number=decrypt_value(guest.id_number)
            )

    # Decrypt CheckInRecord id_numbers
    for record in CheckInRecord.objects.exclude(id_number='').exclude(id_number__isnull=True):
        if record.id_number and is_encrypted(record.id_number):
            CheckInRecord.objects.filter(pk=record.pk).update(
                id_number=decrypt_value(record.id_number)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_data, decrypt_existing_data),
    ]
