# Generated by Django 5.2.7 on 2025-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_loginauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update')], db_index=True, max_length=20),
        ),
    ]
