# Generated by Django 5.2.7 on 2025-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_loginauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh')], db_index=True, max_length=20),
        ),
    ]
