# Generated by Django 5.2.7 on 2025-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_loginauditlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_pictures/'),
        ),
    ]
