# Generated by Django 5.2.7 on 2025-12-17 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_profile_picture'),
        ('hotels', '0007_make_room_type_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel this staff member is assigned to (for staff role only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='hotels.hotel'),
        ),
    ]
