# Generated by Django 5.2.7 on 2025-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_assigned_hotel_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Hashed backup codes for 2FA recovery'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_confirmed',
            field=models.BooleanField(default=False, help_text='Whether 2FA setup has been confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32, null=True),
        ),
    ]
