# Generated by Django 5.2.7 on 2025-12-20 18:42

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_email_verified_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_secret',
            field=core.fields.EncryptedCharField(blank=True, help_text='Encrypted TOTP secret key', max_length=255, null=True),
        ),
    ]
