# Generated by Django 5.2.7 on 2025-12-20 18:43

from django.db import migrations


def encrypt_existing_2fa_secrets(apps, schema_editor):
    """
    Encrypt existing plaintext two_factor_secret values.
    """
    from core.encryption import encrypt_value, is_encrypted

    User = apps.get_model('authentication', 'User')

    for user in User.objects.exclude(two_factor_secret='').exclude(two_factor_secret__isnull=True):
        if user.two_factor_secret and not is_encrypted(user.two_factor_secret):
            User.objects.filter(pk=user.pk).update(
                two_factor_secret=encrypt_value(user.two_factor_secret)
            )


def decrypt_existing_2fa_secrets(apps, schema_editor):
    """
    Reverse migration: decrypt two_factor_secret values back to plaintext.
    """
    from core.encryption import decrypt_value, is_encrypted

    User = apps.get_model('authentication', 'User')

    for user in User.objects.exclude(two_factor_secret='').exclude(two_factor_secret__isnull=True):
        if user.two_factor_secret and is_encrypted(user.two_factor_secret):
            User.objects.filter(pk=user.pk).update(
                two_factor_secret=decrypt_value(user.two_factor_secret)
            )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_encrypt_sensitive_fields'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_2fa_secrets, decrypt_existing_2fa_secrets),
    ]
