# Generated by Django 5.2.7 on 2025-12-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_default_checkin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncillaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('breakfast', 'Breakfast'), ('spa', 'Spa Access'), ('late_checkout', 'Late Checkout'), ('parking', 'Parking'), ('minibar', 'Minibar'), ('laundry', 'Laundry'), ('room_service', 'Room Service'), ('other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('pricing_type', models.CharField(choices=[('per_booking', 'Per Booking'), ('per_person', 'Per Person'), ('per_person_per_day', 'Per Person Per Day'), ('per_day', 'Per Day'), ('one_time', 'One Time')], default='one_time', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_services', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'ancillary services',
                'ordering': ['service_type', 'name'],
            },
        ),
    ]
