# Generated by Django 5.2.7 on 2025-12-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_ancillaryservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonalpricing',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'seasonal pricing'},
        ),
        migrations.RemoveField(
            model_name='roomtypepricing',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='seasonalpricing',
            name='modifier_type',
        ),
        migrations.RemoveField(
            model_name='seasonalpricing',
            name='modifier_value',
        ),
        migrations.RemoveField(
            model_name='seasonalpricing',
            name='priority',
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='off_peak_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Price per night during off-peak season', max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='peak_price',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Price per night during peak season', max_digits=10),
        ),
        migrations.AddField(
            model_name='seasonalpricing',
            name='is_peak_season',
            field=models.BooleanField(default=False, help_text='If true, peak prices apply during this period'),
        ),
        migrations.AlterField(
            model_name='roomtypepricing',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Double'), ('deluxe', 'Deluxe King'), ('suite', 'Family Suite'), ('family', 'Penthouse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seasonalpricing',
            name='season_name',
            field=models.CharField(help_text="e.g., 'Summer Peak', 'Christmas Peak', 'Winter Off-Peak'", max_length=100),
        ),
    ]
