# Generated by Django 5.2.7 on 2025-12-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_simplify_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['gallery_type', 'name'], 'verbose_name_plural': 'galleries'},
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(condition=models.Q(('gallery_type', 'hotel')), fields=('hotel',), name='unique_hotel_gallery'),
        ),
    ]
