# Generated by Django 5.2.7 on 2025-12-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_gallery_options_gallery_unique_hotel_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type_category',
            field=models.CharField(choices=[('standard', 'Standard Double'), ('deluxe', 'Deluxe King'), ('suite', 'Family Suite'), ('penthouse', 'Penthouse')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomtypepricing',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Double'), ('deluxe', 'Deluxe King'), ('suite', 'Family Suite'), ('penthouse', 'Penthouse')], max_length=20),
        ),
    ]
