# Generated by Django 5.2.7 on 2025-12-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_make_room_type_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionaldiscount',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomrate',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roomrate',
            name='room_type',
        ),
        migrations.AlterUniqueTogether(
            name='viewpricing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='viewpricing',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='viewpricing',
            name='view',
        ),
        migrations.DeleteModel(
            name='DayTypePricing',
        ),
        migrations.DeleteModel(
            name='PromotionalDiscount',
        ),
        migrations.DeleteModel(
            name='RoomRate',
        ),
        migrations.DeleteModel(
            name='ViewPricing',
        ),
    ]
