# Generated by Django 5.2.7 on 2025-12-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_extra_pricing_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LateCheckoutRequest',
        ),
    ]
