# Generated by Django 5.2.7 on 2025-12-21 13:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_saved_card_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcard',
            name='expiry_month',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='expiry_year',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
