# Generated by Django 5.2.7 on 2025-12-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_add_no_show_fields'),
        ('core', '0001_initial'),
        ('hotels', '0009_remove_late_checkout_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('all', 'All Staff')], default='all', max_length=20)),
                ('notification_type', models.CharField(choices=[('new_booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('check_in_today', 'Check-in Today'), ('check_out_today', 'Check-out Today'), ('payment_received', 'Payment Received'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('hotel_created', 'Hotel Created'), ('hotel_deleted', 'Hotel Deleted'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('target_hotel', models.ForeignKey(blank=True, help_text='Filter notifications by hotel for managers/staff.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hotels.hotel')),
                ('target_user', models.ForeignKey(blank=True, help_text='Specific user target. If null, uses target_role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read Status',
                'verbose_name_plural': 'Notification Read Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_role', 'target_hotel', '-created_at'], name='core_notifi_target__843c14_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='core_notifi_notific_38b6f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('notification', 'user')},
        ),
    ]
